openapi: 3.0.3
info:
  title: Reservations API
  description: API for managing hotel and restaurant reservations
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: List of users
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created

  /reservations:
    get:
      summary: Get all reservations
      operationId: getReservations
      responses:
        '200':
          description: List of reservations
    post:
      summary: Create a new reservation
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '201':
          description: Reservation created

  /hotels:
    get:
      summary: Get all hotels
      operationId: getHotels
      responses:
        '200':
          description: List of hotels

  /restaurants:
    get:
      summary: Get all restaurants
      operationId: getRestaurants
      responses:
        '200':
          description: List of restaurants

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
    
    Reservation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        reservationDate:
          type: string
          format: date-time
        userId:
          type: integer
          format: int64
        hotelId:
          type: integer
          format: int64
          nullable: true
        roomId:
          type: integer
          format: int64
          nullable: true
        restaurantId:
          type: integer
          format: int64
          nullable: true
        tableId:
          type: integer
          format: int64
          nullable: true
        status:
          type: string
          enum: [PENDING, CONFIRMED, CANCELED]
